# Generated by Django 3.1.7 on 2021-04-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0005_responsekomunikasi_kelompok'),
        ('Dosen', '0003_lecturer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dosen.lecturer')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LO.section')),
            ],
        ),
    ]
