# Generated by Django 3.1.7 on 2021-04-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0004_teaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaches',
            name='nip',
        ),
        migrations.AddField(
            model_name='teaches',
            name='dosen',
            field=models.ManyToManyField(null=True, to='Dosen.Lecturer'),
        ),
    ]
