# Generated by Django 3.1.7 on 2021-04-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0005_auto_20210401_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaches',
            name='dosen',
            field=models.ManyToManyField(to='Dosen.Lecturer'),
        ),
    ]
