# Generated by Django 3.1.7 on 2021-04-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0006_auto_20210401_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaches',
            name='dosen',
        ),
        migrations.AddField(
            model_name='teaches',
            name='dosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dosen.lecturer'),
        ),
    ]
