# Generated by Django 3.1.6 on 2021-04-11 07:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0008_merge_20210408_2011'),
        ('Dosen', '0007_auto_20210403_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotIndeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listbobot', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('batasindeks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LO.section')),
            ],
        ),
    ]
