# Generated by Django 3.1.6 on 2021-02-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lo_a', models.CharField(max_length=1)),
                ('lo_b', models.CharField(max_length=1)),
                ('lo_c', models.CharField(max_length=1)),
                ('lo_d', models.CharField(max_length=1)),
                ('lo_e', models.CharField(max_length=1)),
                ('lo_f', models.CharField(max_length=1)),
            ],
        ),
    ]
