# Generated by Django 3.1.6 on 2021-02-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0002_auto_20210219_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
