# Generated by Django 3.1.6 on 2021-03-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mahasiswa', '0002_auto_20210223_1130'),
        ('LO', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='-', max_length=2)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LO.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahasiswa.student')),
            ],
        ),
    ]
