# Generated by Django 3.1.6 on 2021-03-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mahasiswa', '0002_auto_20210223_1130'),
        ('LO', '0003_takes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseKomunikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penyampaian1', models.IntegerField()),
                ('Penyampaian2', models.IntegerField()),
                ('Penyampaian3', models.IntegerField()),
                ('Penyampaian4', models.IntegerField()),
                ('Konten', models.IntegerField()),
                ('Bahasa', models.IntegerField()),
                ('Penguasaan', models.IntegerField()),
                ('Menjawab', models.IntegerField()),
                ('Media', models.IntegerField()),
                ('Waktu', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LO.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahasiswa.student')),
            ],
        ),
    ]
