# Generated by Django 3.1.6 on 2021-02-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0003_auto_20210219_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='lo',
            name='course_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LO.course', to_field='course_id'),
        ),
    ]
