# Generated by Django 3.1.6 on 2021-03-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0004_responsekomunikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsekomunikasi',
            name='kelompok',
            field=models.IntegerField(default=1),
        ),
    ]
