# Generated by Django 3.1.6 on 2021-02-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0004_auto_20210219_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lo',
            name='course_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LO.course'),
        ),
    ]
