# Generated by Django 3.1.6 on 2021-04-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mahasiswa', '0002_auto_20210223_1130'),
        ('LO', '0005_responsekomunikasi_kelompok'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOSuplemenSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('lo_a', models.FloatField()),
                ('lo_b', models.FloatField()),
                ('lo_c', models.FloatField()),
                ('lo_d', models.FloatField()),
                ('lo_e', models.FloatField()),
                ('lo_f', models.FloatField()),
                ('lo_g', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahasiswa.student')),
            ],
        ),
        migrations.CreateModel(
            name='LOSuplemenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lo_a', models.FloatField()),
                ('lo_b', models.FloatField()),
                ('lo_c', models.FloatField()),
                ('lo_d', models.FloatField()),
                ('lo_e', models.FloatField()),
                ('lo_f', models.FloatField()),
                ('lo_g', models.FloatField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LO.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahasiswa.student')),
            ],
        ),
    ]
