# Generated by Django 3.1.6 on 2021-04-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0005_responsekomunikasi_kelompok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsekerjasama',
            name='course',
        ),
        migrations.RemoveField(
            model_name='responsekerjasama',
            name='student',
        ),
        migrations.RemoveField(
            model_name='responsekomunikasi',
            name='course',
        ),
        migrations.RemoveField(
            model_name='responsekomunikasi',
            name='student',
        ),
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.RemoveField(
            model_name='score',
            name='nim',
        ),
        migrations.AddField(
            model_name='responsekerjasama',
            name='takes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LO.takes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsekomunikasi',
            name='takes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LO.takes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='takes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LO.takes'),
            preserve_default=False,
        ),
    ]
