# Generated by Django 3.1.6 on 2021-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0005_auto_20210219_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='lo',
            name='lo_g',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
