# Generated by Django 2.2.7 on 2021-02-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0006_lo_lo_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sec_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
