# Generated by Django 3.1.6 on 2021-04-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0006_auto_20210408_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='course_id',
            new_name='course',
        ),
    ]
