# Generated by Django 2.2.7 on 2021-02-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0007_auto_20210223_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.IntegerField(),
        ),
    ]
