# Generated by Django 3.1.6 on 2021-04-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0006_losuplemencourse_losuplemensemester'),
        ('LO', '0007_auto_20210408_1350'),
    ]

    operations = [
    ]
