# Generated by Django 2.2.7 on 2021-02-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0008_auto_20210223_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
