# Generated by Django 3.1.6 on 2021-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0009_responsekuesioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='isKuesionerFilled',
            field=models.BooleanField(default=False),
        ),
    ]
