# Generated by Django 3.1.6 on 2021-04-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0010_takes_iskuesionerfilled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssessmentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('section_count', models.IntegerField(default=1)),
                ('section_count_str', models.CharField(max_length=9)),
                ('courseOutcomeScore', models.FloatField()),
                ('kuesionerScore', models.FloatField()),
                ('portfolioScore', models.FloatField(default=4.0)),
                ('finalScore', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LO.course')),
            ],
        ),
    ]
