# Generated by Django 3.1.6 on 2021-03-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mahasiswa', '0002_auto_20210223_1130'),
        ('LO', '0010_bobotkomponenscore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='nim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahasiswa.student'),
        ),
    ]
