# Generated by Django 3.1.6 on 2021-04-22 10:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0011_courseassessmentscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListKomponenScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komponen', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LO.section')),
            ],
        ),
    ]
