# Generated by Django 3.1.6 on 2021-03-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0010_takes'),
        ('LO', '0012_auto_20210302_1908'),
    ]

    operations = [
    ]
