# Generated by Django 3.1.6 on 2021-04-22 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0012_listkomponenscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listkomponenscore',
            name='komponen',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
