# Generated by Django 3.1.6 on 2021-04-22 14:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0014_bobotkomponenscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('takes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LO.takes')),
            ],
        ),
    ]
