# Generated by Django 3.1.6 on 2021-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LO', '0016_takes_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='final_score',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
