# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python3.9 --version  # Print out python version for debugging
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yq
  - pip3 install -r requirements.txt


stages:
 - test


test:
 script:
  - virtualenv --python=python3 venv/
  - source venv/bin/activate
  - pip3 install django
  - python3.9 ./manage.py test
  - source venv/bin/activate
