# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

variables:
  PATH : "C:\\Users\\Gunawan\\AppData\\Local\\Programs\\Python\\Python39\\"

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python --version  # Print out python version for debugging
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - pip install -r requirements.txt


stages:
 - test


test:
 script:
  - python manage.py test
