# Generated by Django 2.2.7 on 2021-02-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='nim',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
